### ISSUE TITLE
Please update drivers for F1!

### ISSUE THREAD

**Issue by xesy** [formuler/meta-formuler#13]
According to 
https://www.formuler.tv/single-post/2017/05/24/F1-Driver-Update
new drivers and kernel (4.10.6) are available. 

Maybe new driver will fix ethernet problems in OpenPLI:
https://forums.openpli.org/topic/54989-formuler-f1-network-issue/
Perhaps new hardware revision was released and 10.2016 drivers in bsp don't work with it.

**Comment by eriksl** [comment]
See the forum for an explanation why it is the way it is.
