### ISSUE TITLE
bug drivers from "20150402"

### ISSUE THREAD

**Issue by Dima73** [formuler/meta-formuler#5]
Bug drivers from "20150402" for DVB-T tuner:

ims openpli
-------------------------------------------------------------
it is a question, how many users using Formuler1 with DVB-T ...
I am using old drivers again and all is ok. With new drivers on most channels each 1s was pixelisation ( apparently signal lost or some in tunner oscillate) and signal bar skipped between 0 - 40% (with old drivers is signal between 50 - 54%).
-------------------------------------------------------------

Dimitrij openpli
---------------------------------------------------------------
Checked.
There are big problems.
They arise when the first zap or start box to service DVB-T.
The decision to switch back and forth between DVB-T -> DVB-S -> DVB-T
--------------------------------------------------------------
ims openpli
-------------------------------------------------------------
As you wrote - helps from DVB-T zap to DVB-S and after several seconds zap back to "problematic" service on DVB-T.
But after zapping acros several next DVB-T channels problem starts again...
--------------------------------------------------------------

**Comment by ims21** [comment]
And with 20150605 was nothing repaired !

**Comment by Dima73** [comment]
solved
